debug: true
spring:
  application:
    name: sistema-inventario-zapatillas
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/inventario_zapatillas
    username: ${DB_USER}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
  config:
    import: optional:file:.env[.properties]

#Esto es para evitar que salga todos los logs en la consola   
logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: ERROR


#Configuracion para Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
  
  
  